load_en_EN <- function() {
  require(rlang)
  env_bind(current_env(), ask_2x2_table ="Table 2x2 ?")
  ask_2x2_table <<- "Table 2x2?"
  ask_2x2_table_value <<- "Please specify the value for tables 2x2"
  ask_add_a_value_to_empty_cells <<- "Does an empty cell value for polychoric correlations need to be added? To specify the values, choose TRUE, otherwise choose [default]"
  ask_add_value_to_total <<- "do you still want to add a total value?"
  ask_analysis_by_group <<- "Group analysis?"
  ask_analysis_on_complete_data_or_remove_outliers <<- "Will you require analysis on the complete data or on the data for which the influential values have been removed?"
  ask_analysis_type <<- "What analysis do you want to make?"
  ask_are_frequences_free_parameters <<- "is the frequency of the different group a free parameter? "
  ask_are_there_inversed_items <<- "Is there any inverse items?"
  ask_are_you_ready <<- "are you ready?"
  ask_baseline <<- "What is the baseline?"
  ask_bigger_tables_value <<- "Please specify the value for tables larger than 2x2"
  ask_bootstrap_number_min_500 <<- "Please specify the number of bootstrap. A minimum of 500 is ideally required. Can take time for N>1000"
  ask_bootstrap_numbers_1_for_none <<- "Please specify the number of bootstrap. To not have bootstrap, choose 1"
  ask_bootstraps_number <<- "Number of bootstraps?"
  ask_cancel_entered_value_not_num <<- "the value you entered is not numerical. Do you want to cancel this analysis?"
  ask_cauchy_apriori_distribution <<- "Please specify the prior distribution of Cauchy"
  ask_center <<- "Center?"
  ask_center_numeric_variables <<- "Do you want to focus the numerical variables? Centrer is generally advised (e.g., Schielzeth, 2010). "
  ask_chi_squared_type <<- "Please specify the type of chi tile you want to achieve."
  ask_choose_a_variable_with_at_least_two_modalities <<- "A categorical variable must have at least 2 different modes. Please choose a variable with at least two modes"
  ask_chose_analysis <<- "Please choose the analysis you want to perform."
  ask_chose_categorial_ranking_factor <<- "Please select the categorical classification factor."
  ask_chose_cols_corresponding_to_repeated_measures <<- "Please choose all the columns corresponding to the modalites of the variables in repetees measures"
  ask_chose_covariables <<- "Please choose the covariates"
  ask_chose_database <<- "Please select the database"
  ask_chose_defining_groups <<- "Please select the group definition"
  ask_chose_dependant_variable <<- "Please select the dependent variable. "
  ask_chose_first_judge <<- "Please select the first judge"
  ask_chose_independant_group_variables <<- "Please choose the variables-s with independent groups"
  ask_chose_interaction_model_predictors <<- "Please choose the predictors to enter into the interaction model. It is necessary to have at least two variables"
  ask_chose_manifest_variables_at_least_three <<- "Please select the obvious variables you want to analyze. You must choose at least 3 variables"
  ask_chose_ranking_categorial_factor <<- "Please select the categorical classification factor."
  ask_chose_rotation <<- "Please choose the type of rotation. Objection is adapted in the humanities"
  ask_chose_sample_variables <<- "Please select the variable(s) defining the workforce"
  ask_chose_second_judge <<- "Look for the second judge"
  ask_chose_selection_method <<- "Please choose the selection method you wish to use"
  ask_chose_the_working_dir <<- "Please select work directory"
  ask_chose_variables_at_least_five <<- "Please select the variables you want to analyze. You must choose at least 5 variables"
  ask_chose_variables_at_least_three <<- "Please select the variables you want to analyze. You must choose at least 3 variables"
  ask_chose_variable <<- "Please choose the variables you want to analyze."
  ask_chose_variable_x_axis <<- "Please select the abscess variable"
  ask_chose_variable_y_axis <<- "Please select the variable ordered"
  ask_coding_criterion <<- "What coding criteria do you want?"
  ask_col_separation_index <<- "When saving your file, what is the column separation index?"
  ask_complete_or_outliers <<- "Do you want to perform analyses on complete data or on data without influential values?"
  ask_constant_parameters <<- "Consistent parameters?"
  ask_continue <<- "Continue?"
  ask_contrast_must_respect_ortho <<- "Contrasts must respect orthogonalite. Do you want to continue?"
  ask_control_variables <<- "Please specify the variable(s) to control"
  ask_convert_dependant_variable_to_dichotomic <<- "do you want to convert the dependent variable into a dichotomous variable?"
  ask_correction_desired <<- "Please specify the type of probability correction you want to achieve"
  ask_correction_type <<- "Type of correction?"
  ask_correlated_or_orthogonal_factors <<- "Is the factors correlated (FALSE) or are they orthogonal (TRUE)?"
  ask_correlation_matrix_could_not_be_computed <<- "The correlation matrix could not be achieved. Do you want to try again?"
  ask_correlation_type <<- "Please choose the type of correlations you want to make. For dichotomous variables, correlations will be tetrachoric correlations"
  ask_corr_or_partial_correlations <<- "Partial corrections or correlations?"
  ask_could_not_converge_model_verify_correlation_matrix <<- "We did not succeed in making the model converge. Please check your correlation matrix and try again with other parameters"
  ask_could_not_finish_analysis_respecify_parameters <<- "We were unable to complete the analysis correctly. Please try to respecify the parameters"
  ask_covariables <<- "Covariable-s?"
  ask_criterion_for_dichotomy <<- "Please specify the criteria on which you want to dichotomize your variable. You can use the mediane or choose a specific threshold. "
  ask_criterion_for_obs_to_keep <<- "Please specify the criteria for any comments you wish to keep/guard."
  ask_criterion_for_variable <<- "What criteria do you want to use for the variable"
  ask_data <<- "Données?"
  ask_data_format <<- "What is the format of your data?"
  ask_decimal_symbol <<- "If some data contain decimals, what is the symbol indicating the decimal?"
  ask_denominator_variable_or_value <<- "Is the denominator a variable or a value? "
  ask_denominator_variable <<- "Please select the variable to the denominator "
  ask_dependant_variable_with_less_than_three_val_verify_dataset <<- "The dependent variable has less than three different values. Check your data or the analysis you are trying to do is not relevant."
  ask_did_not_specify_nb_factors_repeated_measure_exit <<- "You haven't specified the number of factors you can repetee, do you want to quit?"
  ask_distribution <<- "Distribution?"
  ask_distribution_type <<- "What distribution do you want?"
  ask_empty_cells <<- "Old Cells?"
  ask_enter_different_values <<- "Please enter different values"
  ask_enter_number_of_to_be_removed_variable <<- "You must enter the number to know which observation should be deleted."
  ask_exit_because_of_alpha_on_non_matrix <<- "You are trying to do an alpha on something other than a matrix. Do you want to leave this analysis?"
  ask_exit_no_lower_bound_specified <<- "You have not specified the lower limit. Do you want to leave the selection?"
  ask_exit_no_upper_bound_specified <<- "You have not specified the upper limit. Do you want to leave the selection?"
  ask_exportation_filename <<- "What name do you want to assign to the file?"
  ask_factorial_scores <<- "factorial scores?"
  ask_factors_number_for_hierarchical_structure <<- "Please specify the number of factors in the hierarchical structure. "
  ask_factors_ortho <<- "Orthogonalitis of factors?"
  ask_factors_superior_level <<- "Number of factors of the higher level?"
  ask_family <<- "Please specify the family (i.e. form of distribution). "
  ask_file_format <<- "File format?"
  ask_file_format_to_import <<- "What format is your file saved?"
  ask_first_categorical_set <<- "Please select the first categorical factor(s) set"
  ask_first_variables_set <<- "Please select the first set of variables"
  ask_fixed_covariables <<- "fixed covariates?"
  ask_freq_constance <<- "Constance of Frequence?"
  ask_f_value <<- "What value do you want to use?"
  ask_group_variable <<- "Variable [groups]?"
  ask_headers_in_database <<- "Is the name of the variables on the first line of your database? Choose TRUE if so"
  ask_hierarchical_analysis <<- "Does it have to make a hierarchical analysis?"
  ask_how_many_modalities <<- "How many modes"
  ask_how_standard_error_must_be_estimated <<- "How should the standard error be estimated?"
  ask_how_to_remove <<- "How do you want to delete them?"
  ask_how_to_treat_missing_values <<- "Missing values were detected. How do you want to treat them? Keeping all observations can bias the results. "
  ask_id_variable <<- "Please select the variable identifying participants"
  ask_imitate <<- "Imitate?"
  ask_independant_variable <<- "Please select the independent variable. "
  ask_information_matrix <<- "Information Matrix?"
  ask_integrate_factorial_scores_in_data <<- "Do you want factorial scores to be integrated with your data?"
  ask_inversed_items <<- "inverse items?"
  ask_is_model_correct <<- "Is your model correct?"
  ask_latent_variables_number <<- "Please specify the number of latent variables"
  ask_level <<- "Please select level"
  ask_likelihood <<- "Treasure?"
  ask_linebase_modalities <<- "Please specify the mode(s) that will be used for the base line (e.g. 0). The other modes will be grouped in category 1."
  ask_log_base <<- "Please specify the base of the logarithm.To get e, type e"
  ask_lower_bound <<- "Inferior limit?"
  ask_mcnemar_repeated_measure <<- "McNemar test: modalites are not the same for the McNemar test. Is this a factor that is able to repeat?"
  ask_mediation_type <<- "What kind of mediation?"
  ask_mediator <<- "please choose the mediator"
  ask_minus_left_hand_variables <<- "Please select the variable(s) on the left of the symbol *minus*"
  ask_minus_right_hand_variables <<- "Please select the variable(s) on the right of the symbol *minus*."
  ask_minus_right_operand_variable_or_value <<- "Are the values on the right of the symbol *minus* a variable(s) or a value? "
  ask_missing_values_detected_what_to_do <<- "Missing values have been detected. How do you want to treat them?"
  ask_missing_values_treatment <<- "Treatment of missing values?"
  ask_missing_values_value_na_on_empty <<- "If some data is missing, how are they defined? You can leave NA if the cells are empty."
  ask_missing_value_treatment <<- "Number of missing values per variable. How do you want to treat them?"
  ask_modalities_for_variable <<- "What modes do you want to select for the variable"
  ask_modalities_to_keep <<- "Please select the modes you want to keep."
  ask_name_for_dataset <<- "What name do you want to give the data?"
  ask_name_to_attribute_to <<- "What name do you want to assign to"
  ask_nb_factors_repeated_measure <<- "How many factors can be rehearsed?"
  ask_new_variable_name <<- "What name do you want to assign to the new variable? "
  ask_norm_value <<- "What is the standard value?"
  ask_not_enough_obs_verify_dataset <<- "There are not enough observations to make the analysis. Please check your net data to ensure that there are at least three observations per mode of each factor"
  ask_null_hypothesis_tests_or_bayesian_factors <<- "Do you want null hypothesis tests or/and Bayesian factors?"
  ask_numerator_variable_or_value <<- "Is the numerator a variable or a value? "
  ask_numerator_variable <<- "Please select the variable at the numerator "
  ask_obs_to_remove <<- "What observation do you want to remove from analyses? 0=none"
  ask_other_options <<- "Other options?"
  ask_ponderate_analysis_by_a_sample_var <<- "Does the analysis need to be weighted by an effective variable?"
  ask_positive_val_variable_or_value <<- "Are the positive values a variable(s) or a value? "
  ask_predictor <<- "please specify the predictor"
  ask_press_enter_to_continue <<- "Support [enter] to continue"
  ask_probabilities_for_modalities <<- "Please enter the probabilities corresponding to each mode of the variable. "
  ask_probabilities <<- "Probability?"
  ask_probability_value <<- "What value of probability do you want to use?"
  ask_redefine_analysis_because_modalities_product_is_superior_to_obs <<- "The product of the modalites of the variables defining the groups is superior to your observations. You need at least one observation by combination of modes of your variables. Please redefine your analysis"
  ask_regroup_modalities <<- "Do you want to group between the modes?"
  ask_rename_variables_with_special_char <<- "Some variable names contain special characters that can create bugs. Do you want to rename these variables?"
  ask_results_desired <<- "What results do you want?"
  ask_results_output <<- "Outcomes?"
  ask_sampling_type <<- "What type of sampling have you done for your analysis?"
  ask_save_results_in_external_file <<- "Do you want to save results to an external file?"
  ask_second_categorical_set <<- "Please select the second categorical factor(s) set"
  ask_second_mediator <<- "Please specify the second mediator. "
  ask_second_variables_set <<- "Please select the second set of variables"
  ask_selection_method <<- "What method should be used for the selection method?"
  ask_select_variables_or_modalities_of_repeated_measure_variable <<- "Please select the variables OR modalites of the variables a measure(s). "
  ask_separation_value <<- "Please specify the separation value"
  ask_shorten_long_variables_names <<- "Some variables have particularly long names that can generate playback. Do you want to shorten them?"
  ask_should_intercept_of_latent_variable_be_fixed_to_zero <<- "Does the intercept of latent variables have to be fixed to 0?"
  ask_should_intercept_of_obs_variables_be_fixed_to_zero <<- "Does the intercept of observed variables have to be fixed to 0?"
  ask_simple_or_partial_corr <<- "Single or partial corrections?"
  ask_specify_all_parameters_or_imitate_specific_software <<- "Do you want to specify all the parameters [default] or imitate any particular software?"
  ask_specify_datasheet_to_import <<- "Please specify the worksheet you want to import"
  ask_specify_groups <<- "Specify groups?"
  ask_specify_inverted_item <<- "Please specify the inverse items"
  ask_specify_likelihood <<- "Please specify the likelihood. "
  ask_specify_norm_value <<- "Please specify the value of the standard"
  ask_specify_other_options <<- "Specify other options?"
  ask_specify_sample <<- "Specify actual?"
  ask_specify_sample_variable <<- "Specify the true number?"
  ask_specify_variables_for_ranks <<- "Please specify the variables you wish to make the rows of"
  ask_specify_variables_type <<- "Please specify the type(s) of variable(s) you wish to include in the analysis.nYou can choose several (e.g., for mixed anova or ancova)"
  ask_standard_error <<- "Standard Error?"
  ask_standardization <<- "Standardization?"
  ask_standardization_vl <<- "Standardization VL?"
  ask_standardize_obs_variables_before <<- "Does it standardize (i.e. centrer reduce) the variables observed at prelable (TRUE) or not (FALSE)?"
  ask_statistical_approach <<- "Statistical approach?"
  ask_subgroups <<- "You can compose descriptive statistics by sub-group by choosing one or more categorical variables. Do you want to specify the subgroups?"
  ask_sufficient_matrix_for_afe <<- "Is the matrix satisfactory for an EFA?"
  ask_suppress_this_obs <<- "Do you want to delete this observation?"
  ask_test_hierarchical_structure <<- " Do you want to test a hierarchical structure? The omega tests a hierarchical structure and a hierarchical AFE will be realized."
  ask_time1 <<- "Please choose time 1."
  ask_time2 <<- "Please choose time 2."
  ask_transform_numerical_to_categorial_variables <<- "You must use categorical variables. Do you want to turn numerical variables into categorical variables?"
  ask_troncature_threshold <<- "Please set the threshold of the trunk"
  ask_t_test_type <<- "Please specify the type of test t you want to perform."
  ask_type_correlation <<- "Please specify the type of correlation you want to achieve."
  ask_upper_bound <<- "High light?"
  ask_value_for_missing_values <<- "By what value are the missing values defined?"
  ask_value_for_operation <<- "Please specify the value for your mathematical operation. "
  ask_value_for_selected_obs <<- "Please specify the value on which observations should be selected. "
  ask_value <<- "Get value?"
  ask_variabels_for_polyc_tetra_mixt_corr <<- "Please select the variables for which polychoric/tetrachoric/mixte correlations should be made."
  ask_variable_at_this_point <<- "What variable has this etape"
  ask_variable_name <<- "Name of new variable?"
  ask_variables_for_description_statistics <<- "Please choose the variables for which you wish to obtain descriptive statistics"
  ask_variables_groups <<- "Variable groups?"
  ask_variables_names <<- "Name of variables?"
  ask_variables_to_abs <<- "Please select the variables to make the absolute value "
  ask_variables_to_add <<- "Please select the variables to add."
  ask_variables_to_exp <<- "Please select the variables to which the exponent applies"
  ask_variables_to_log <<- "Please select the variables for which logarithm is required"
  ask_variables_to_mean <<- "Please select the variables to average "
  ask_variables_to_multiply <<- "Please select the variables to multiply. "
  ask_variables_to_order <<- "Please select the variable(s) to sort"
  ask_variables_type_correlations <<- "Please specify the type of variables. Tetra/polychoric correlations will be made on dichotomous/ordinal variables and Bravais-Pearson on continuous variables"
  ask_variables_types_correlations <<- "Please specify the type of variables. Tetra/polychoric correlations will be made on the ordinal and Bravai-Pearson variables on the continuous"
  ask_variables_used_for_exponential <<- "Please select the variables used in the exhibition "
  ask_variables_used_for_groups <<- "Please select the variable(s) defining groups"
  ask_variable <<- "Variable to analyze?"
  ask_wanted_model <<- "Please choose the model you want to analyze with aov.plus"
  ask_what_do_you_want <<- "What do you want?"
  ask_what_is_your_choice <<- "What is your choice?"
  ask_what_to_print <<- "What do you want to show?"
  ask_which_algorithm <<- "What algorithm will you want?"
  ask_which_analysis_you_looking_for <<- "What analysis are you looking for?"
  ask_which_baseline <<- "What is the baseline?"
  ask_which_constant_parameters <<- "What parameters do you want to maintain constant?"
  ask_which_contrasts_for_variable <<- "What contrasts for the variable"
  ask_which_contrasts <<- "What kind of contrast do you want?"
  ask_which_correction <<- "What correction of probability do you want to apply? To not apply a correction, choose +none+"
  ask_which_data_to_analyse <<- "What data do you want to analyze?"
  ask_which_data_to_export <<- "What data do you want to export?"
  ask_which_estimator <<- "What estimator?"
  ask_which_factors_combination_for_adjust_means <<- "What combination of factors do you want to show the adjusted averages?"
  ask_which_information_matrix_for_standard_error_estimation <<- "On which information matrix should the estimation of standard errors be achieved?"
  ask_which_mathematical_operation <<- "Please choose the mathematical operation you wish to achieve"
  ask_which_operation <<- "What operation do you want?"
  ask_which_options <<- "What options?"
  ask_which_options_to_specify <<- "What options do you want to specify?"
  ask_which_output <<- "What format do you want?"
  ask_which_output_results <<- "What results do you want?"
  ask_which_regression_type <<- "What type of regression?"
  ask_which_results_warning_on_default_output <<- "What results do you want? Warning: exits by default cannot be saved. If you want a saver, choose the detail"
  ask_which_rotation <<- "What rotation"
  ask_which_saturation_criterion <<- "What is the saturation criteria you want to use?"
  ask_which_size_effect <<- "What effect size do you want?"
  ask_which_squared_sum <<- "What sum of squares do you want to use?"
  ask_which_test <<- "What test do you want to use?"
  ask_which_value_for_operation <<- "What value do you want for your mathematical operation?"
  ask_which_variable_identifies_participants <<- "What is the variable identifying participants?"
  ask_you_did_not_chose_a_variable_continue_or_abort <<- "You have not chosen a variable. Do you want to continue (ok) or give up (cancel) this analysis?"
  desc_abs_val_applied_to_var <<- "the absolute value has been applied to the variable"
  desc_accepted_values_are_z_and_grubbs <<- "The values accepted for criteria are z and Grubbs "
  desc_all_tests_description <<- "The parametric model returns the classic anova, the nonparametric calculates the Kruskal Wallis test nsi it is a model with independent groups, or a Friedman anova for a model in Measurements repetees.nThe Bayesian model is the equivalent of the model test in the anova by adopting a Bayesian approach,n the robust statistics are anovas on medianes or the truncated averages with or without bootstrap."
  desc_alpha_increased_with_value_equals_to <<- "you multiply the error of 1e espece. The risk of making an error of 1st species is"
  desc_analysis_aborted <<- "The analysis could not be completed"
  desc_and <<- "and"
  desc_and_variabe <<- "and variable"
  desc_and_variable_y <<- " and variable "
  desc_applied_correction_is <<- "the correction applied is the correction of"
  desc_at_least_10_obs_needed <<- "It takes at least 10 observations plus the number of variables to make the analysis. Check your data."
  desc_at_least_independant_variables_or_repeated_measures <<- "It is essential to have at least variables with independent groups or in repete measures"
  desc_at_least_on_contrast_matrix_incorrect <<- "At least one of your contrast matrices is not correct."
  desc_at_least_one_denom_is_zero <<- "At least one of the values in the denominator is a 0. The value returned in this case is infinite - inf"
  desc_at_least_one_non_numeric <<- "at least one variable is not digital"
  desc_at_least_one_var_is_not_num <<- "at least one of the variables is not numerical"
  desc_authorized_values_for_contrasts <<- "The permitted values for contrasts are +none+ for no contrast, +pairwise+ for comparisons 2 to 2 or a list of contrast coefficients"
  desc_avoid_spaces_and_punctuations <<- "Avoid spaces and punctuation signs, except . and _ "
  desc_bayesian_factors_could_not_be_computed <<- "Bayesian factors could not be calculated. "
  desc_beyond_with_lower_and_upper <<- "au-dela (with a lower and higher limit)"
  desc_biased_results_risk_because_of_low_number_of_obs_or_zero_variance <<- "there are less than 3 observations for one of the groups or nthe variance of at least one group is 0. Results are likely to be significantly biased"
  desc_bootstraps_number_must_be_positive <<- "The number of bootstrap must be a positive integer"
  desc_bootstrap_t_adapt_to_truncated_mean <<- "The bootstrap-t method is a bootstrap adapted to the calculation of the truncate mean"
  desc_cannot_compute_mahalanobis <<- "Desole, we cannot calculate the distance of Mahalanobis on your data. The analyses will be carried out on the complete data"
  desc_cannot_group_variables_because_not_described <<- "You cannot have a variable *groups* since all variables must be descripted"
  desc_cannot_have_both_within_RML_arguments <<- "You cannot have both arguments in within and RML"
  desc_cells_for_mcnemar <<- "The cells used to calculate the McNemar are those of the 1st row 2nd column and the 2nd row 1st column"
  desc_centered_data_schielzeth_recommandations <<- "In accordance with the recommendations of Schielzeth 2010, the data were pre-centered"
  desc_chi_squared_adjustment_on_variable_x <<- "chi two adjustment on variable"
  desc_close_browser_to_come_back <<- "Do not forget to close the htmlt window (firexfox, chrome, internet explorer...) to return to the R session"
  desc_cross_validation_is_not_yet_supported <<- "Cross validation is not yet available. "
  desc_data_saved_in <<- "data are saved in"
  desc_data_succesfully_ordered <<- "data have been sorted correctly "
  desc_descriptive_statistics_on <<- "Descriptive statistics on"
  desc_distribution_is_hypergeometric_when <<- "The option *Total fixed effect for rows and columns* when the totals for rows and columns are fixed. The distribution is hypergeometric"
  desc_each_participant_must_appear_only_once_ <<- "Each participant must appear once and only once for each combination of the modes"
  desc_effect_size_by_walker <<- "The effect size is calculated from the formula proposed by Walker, 2003"
  desc_entered_value_not_num <<- "value entered is not numerical"
  desc_exponential_has_been_applied_to_var <<- "exponential has been applied to the variable"
  desc_facotrs_must_be_positive_int_inferior_to_variables_num <<- "The number of factors must be a positive integer less than the number of variables"
  desc_fb_ratio_between_models <<- "FB ratio between models"
  desc_file_is_saved_in <<- "file is saved in"
  desc_flattening_and_asymetry_configurable <<- "You can specify truncation and parameters for flattening and asymetry by choosing other options"
  desc_for_bigger_samples_bootstrap_t_prefered <<- "For larger samples, boostrap using method t should be preferred."
  desc_for_easier_to_work <<- "In order for easieR to work properly, Pandoc must be installed at the following URL: https://github.com/jgm/pandoc/releases"
  desc_graph_thickness_gives_density <<- "The thickness of the graph gives the density, allowing to better define the distribution. "
  desc_has_been_added_to <<- "was added to"
  desc_has_been_added_to_variable <<- "is added to variable"
  desc_has_been_applied_to_variable <<- " has been applied to the variable"
  desc_has_been_put_to_the_power_of <<- " has been elevated to power"
  desc_has_multiplied_variables <<- "a multiplies the -les-variables"
  desc_highest_value <<- "Highest Value"
  desc_how_to_cite_easier <<- "To cite easieR in your publication / to quote easieR in you publications use:n Stefaniak, N. (2020). "
  desc_identical_option_total_sample <<- "The total fixed staffing option for columns* is identical to the previous one for columns"
  desc_identified_outliers <<- "Observations considered influential"
  desc_if_true_covariates_as_fixed <<- "If true, exogenous covaria are considered fixed, otherwise they are considered to be aleatory and their parameters are free"
  desc_if_true_latent_residuals_one <<- "If true, the residuals of latent variables are fixed to 1, otherwise the parameters of the latent variable are estimated by setting the first indicator to 1"
  desc_improve_likelihood_for_each_variable <<- "Improving likelihood for each variable"
  desc_incorrect_model <<- "The specified model is incorrect. Check your variables and model"
  desc_instable_model_high_multicolinearity <<- "Multicolinearite is too important. The model is unstable"
  desc_insufficient_obs <<- "The number of observations is insufficient to complete the analyses for this group"
  desc_insufficient_sample_for_combinations_between <<- "The number of combinations between the variable is insufficient "
  desc_in_that_case_non_parametric_is_classical_chi_squared <<- "In this case, the nonparametric test is the classic chi square test"
  desc_issue_in_hierarchical_regression <<- "A problem has been identified in the stages of your hierarchical regression"
  desc_kmo_could_not_be_computed_verify_matrix <<- "The KMO could not be calculated. Check your correlation matrix."
  desc_kmo_must_strictly_be_more_than_a_half <<- "the KMO must be absolutely superior to 0.5"
  desc_kmo_on_matrix_could_not_be_obtained <<- "The KMO on the matrix could not be obtained."
  desc_kmo_on_matrix_could_not_be_obtained_trying <<- "The KMO on the matrix could not be obtained. We try to achieve a smoothing of the correlation matrix"
  desc_large_format_must_be_numeric_or_integer <<- "If your data is in large format, all measurements must be numerical or integer"
  desc_list_of_objects_still_in_mem <<- "List of objects still in memory of R"
  desc_log_with_base <<- "the basic logarithm"
  desc_manifest_variables_of <<- "Manifest Variables of"
  desc_manual_contrast_need_coeff_matrice <<- "If you enter contrasts manually, all variables in the analysis must have their coefficient matrix"
  desc_matrix_is_singular_mardia_cannot_be_performed <<- "The matrix is singular and the Marida test cannot be performed. Only univariate analyses can be carried out"
  desc_mcnemar_need_2x2_table_yours_are_different <<- "The McNemar test involves a 2x2 array. The dimensions of your table are different. "
  desc_modalities_product_must_correspond_to_cols_selected <<- "the output of the modes of each variable must correspond to the number of columns selected. "
  desc_model_contains_error <<- "The model cannot be evaluated. It must contain an error."
  desc_model_could_not_converge <<- "The model could not converge. The parameters have been adapted to allow the model to converge"
  desc_model_seems_incorrect_could_not_be_created <<- "The model seems incorrect and could not be created."
  desc_most_common_effect_size <<- "the most frequent effect size is the partial square - pes.nThe most precise effect size is the generalized square - ges"
  desc_multicolinearity_risk <<- "multicolinearite risk if matrix determinant is less than 0.00001"
  desc_multiple_ways_to_compute_squares_sum <<- "There are several ways to calculate the sum of squares. The default choice of commercial software is a sum of type 3 squares, prioritizing interactions rather than main effects. "
  desc_must_be_dichotomic <<- "modalites. It is incompatible with a logistic regression. It must be dichotomous."
  desc_nb_factors_must_be_positive_integer <<- "The number of factors must be a positive integer less than the number of factors"
  desc_need_at_least_three_observation_by_combination <<- "Some combinations of modes have less than 3 observations. You must have at least 3 observations for each combination"
  desc_neg_log_impossible <<- "it is not possible to calculate logarithms for a base is negative. NA is fired"
  desc_no_analysis_can_be_performed_given_your_data <<- "The variables you selected to perform your analysis do not allow any analysis to be made. Please redefine your analysis"
  desc_no_data_in_R_memory <<- "there are no data in the memory of R, please import the data on which to perform the analysis"
  desc_non_equal_independant_variable_modalities_occurrence <<- "The number of occurrences for each modeite of your independent variable is not the same. Please select a participating identifier"
  desc_non_numeric_value <<- "The input value is not numerical, you must enter a numeric value"
  desc_non_numeric_variable <<- "the variable is not digital"
  desc_non_param_are_rho_and_tau <<- "The nonparametric test corresponds to the Spearman rho and the Kendall tau"
  desc_non_param_is_wilcoxon_or_mann_withney <<- "The non-parametric test is the Wilcoxon test (or Mann-Whitney)"
  desc_no_obs_for_combination <<- "no observations for combination"
  desc_no_result_saved <<- "no result has been saved"
  desc_norm_must_be_numeric <<- "The standard must be a numeric value. "
  desc_no_saved_analysis_found <<- "No backup analysis could be found"
  desc_number_of_judge_is <<- "the number of judges ="
  desc_number_of_missing_values <<- "Number of missing values per variable"
  desc_number_of_observations_is <<- "number of observations ="
  desc_number_outliers_removed <<- "Number of observations withdrawn"
  desc_obs_with_asterisk_are_outliers <<- "The observations marked with an asterisk are considered to be influential at least on a criteria"
  desc_odd_ratio_cannot_be_computed <<- "Or cannot be calculated for tables larger than 2x3 or tables containing 0"
  desc_only_one_dependant_variable_alllowed <<- "There can be only one dependent variable. "
  desc_only_one_file_format_at_time_EPS_JPG <<- "Only one file format for saving figure may be used at a time (you have both EPS and JPG specified). "
  desc_only_one_file_format_at_time_EPS_PDF <<- "Only one file format for saving figure may be used at a time (you have both PDF and EPS specified). "
  desc_only_one_file_format_at_time_PDF_JPG <<- "Only one file format for saving figure may be used at a time (you have both PDF and JPG specified). "
  desc_only_values_above_diagonal_are_adjusted_for_multiple_comp <<- "Only values above the diagonal are adjusted for multiple comparisons"
  desc_operation_succesful <<- "Mathematic operation has gone smoothly."
  desc_order <<- "sort"
  desc_outliers_identified_on_4_div_n <<- "Influential values are identified based on 4/n"
  desc_outliers_identified_on_mahalanobis <<- "Influential values are identified based on the distance of Mahalanobis with a chi threshold at 0.001"
  desc_outliers_on_4_div_n <<- "Influential values are identified on the basis of 4/n"
  desc_packages_used_for_this_function <<- "Packages used for this function"
  desc_param_is_BP <<- "The parametric test is the Bravais-Pearson correlation"
  desc_param_is_t_test <<- "The parametric test is the classic t test"
  desc_param_test_is_classical_reg_robusts_are_m_estimator <<- "The parametric test is the classic regression and robust tests are an estimate on an M estimater as well as a bootstrap."
  desc_percentile_bootstrap_prefered_for_small_samples <<- "the percentile boottrap method must be preferred for small samples"
  desc_perfectly_correlated_variables_in_matrix_trying_to_solve <<- "you try to make a matrix of correlations with perfectly correlated variables. This is a concern for the calculation of Mahalanobis' distance. We are trying to solve the problem."
  desc_polyc_correlations_failed_rho_used_instead <<- "Polychoric correlations have failed. The correlations used are Spearman rho"
  desc_proba_and_IC_estimated_on_bootstrap <<- "Probabilities and ICs are estimated on the basis of a bootrap. The IC is corrected for multiple comparison, unlike the probability reported."
  desc_probabilities_vector_please_no_fraction <<- "Vector of probabilities. Note: do not enter fractions"
  desc_red_dot_is_mean_error_is_sd <<- "The red dot is the average. The error bar is the scale-type"
  desc_references <<- "References for packages used for this analysis"
  desc_removed_variable <<- "deleted variable"
  desc_removing_outliers_weakens_sample_size <<- "Removal of influential values results in too small a number of modalites to complete the analysis"
  desc_result_succesfully_imported_in <<- "Results were correctly imported into"
  desc_robusts_statistics_could_not_be_computed <<- "The robust statistics could not be achieved"
  desc_robust_statistics_are_alternative_to_the_principal_but_slower <<- "The robust statistics are alternative to the main analysis, usually involving bootstraps. These analyses are often slower"
  desc_saturation_criterion_must_be_between_zero_and_one <<- "The saturation criterion must be between 0 and 1."
  desc_search_here <<- "Type your search here"
  desc_selected_obs_are_in <<- "the observations you have selected are in"
  desc_selection_for_bayesian_factor_does_not_apply_to_complex_models <<- "The selection methods for Bayesian factors do not apply for complex models. "
  desc_should_specify_nb_factors_repeated_measure <<- "you need to specify the number of factors you can repetee"
  desc_single_dependant_variable_allowed_in_paired_t <<- "There can be only one dependent variable for tstudents for matched samples"
  desc_singular_matrix_mahalanobis_on_max_info <<- "Your matrix is singular, which is a concern. We are trying to solve the problem. If possible, the distance from Mahalanobis will then be calculated on the maximum information while avoiding the singularite. "
  desc_some_values_are_not_numeric <<- "Not all entered values are numeric. Please enter numeric values only"
  desc_special_characters_have_been_removed <<- "Special accents/characters have been deliberately removed to ensure the portability of easieR on all computers. "
  desc_specify_f_value <<- "You must specify the value of the F. This value must be greater than 1"
  desc_specify_lower_bound <<- "you must specify the lower limit"
  desc_specify_probability_value <<- "You must specify the value of probability. This value shall be between 0 and 1"
  desc_specify_upper_bound <<- "you must specify the upper limit"
  desc_standardized_saturation_on_correlation_matrix <<- "standardized saturations based on the correlation matrix"
  desc_succesfully_imported <<- "data were imported correctly"
  desc_succesful_operation <<- "Operation has been done correctly"
  desc_tested_model_is <<- "the model test is"
  desc_there_is_no_rotation <<- "there is no rotation"
  desc_the_variable_lower <<- "variable"
  desc_the_variable_upper <<- "The variable"
  desc_this_analysis_will_not_be_performed <<- ". This analysis will not be done."
  desc_this_index_is_prefered_for_most_cases <<- " This index is adapted in most situations. The modified M-estimator must be preferred for N<20"
  desc_this_is_large_format <<- "this is the wide format"
  desc_this_is_long_format <<- "this is the long format"
  desc_times_less <<- "times less"
  desc_times_more <<- "times more"
  desc_to_display_results_use_summary <<- "To display the results, please use summary(model.cfa)"
  desc_total_observations <<- "total number of observations"
  desc_truncature_on_m_estimator_adapts_to_sample <<- "The truncation on the M-estimetor adapts to the characteristics of the sample. "
  desc_two_cols_are_needed <<- "For a large-format repeat factor, it takes at least two columns"
  desc_two_modalities_for_independante_categorial_variable <<- "You must use an independent categorical variable with 2 modes"
  desc_unauthorized_char_replaced <<- "Unauthorized characters were used for the name. These characters were replaced by points"
  desc_unavailable_distal_mediations <<- "Distal mediations are not currently available / Distal mediations are not available for now"
  desc_user_exited_aov_plus <<- "you left aov.plus"
  desc_value_must_be_between_zero_and_one <<- "The value must be between 0 and 1"
  desc_value_must_be_numeric <<- "The value must be numerical and between the minimum and maximum of the dependent variable. "
  desc_variable_added <<- "Variable adds"
  desc_variable_must_be_numeric_and_of_non_null_variance <<- "the variable must be digital and have a nonzero variance. "
  desc_variable_must_be_positive_int <<- "the variable must be a positive *integer* integer"
  desc_variables_are_in <<- "selected variables are in"
  desc_we_could_not_compute_anova_on_medians <<- "Desole, we could not calculate the anova on the medianes, possibly due to a large number of ex aequo."
  desc_we_could_not_compute_robust_anova <<- "Desole, we couldn't calculate the robust anova. "
  desc_working_dir_is_now <<- "The work directory is present"
  desc_you_can_chose_predefined_or_manual_contrasts <<- "You can choose predefined contrasts or specify them manually. In the latter case, please choose to specify the contrasts"
  desc_you_can_still_add <<- "You can still add a specific value to the total. Leave 0 if you don't want to add anything"
  desc_you_can_still_multiply <<- "You can still multiply the total by a specific value. Leave 1 if you no longer want to multiply by a new value"
  desc_you_did_this_operation <<- "you have done the following operation:"
  desc_you_exited_afe <<- "you left the AFE"
  desc_you_have_selected <<- "you have selected"
  desc_you_must_give_obs_number <<- "You must enter the observation number"
  desc_your_dependant_variable_has <<- "Your real dependent a"
  desc_z_must_be_a_number <<- "z must be a number"
  desc_author <<- "author: 'Generate automatically by easieR'"
  desc_title <<- "title: 'Results of your analyses'"
  txt_absolute_value <<- "absolute"
  txt_added_variables_graph <<- "Added variable scale"
  txt_additions <<- "adds"
  txt_additive_effects <<- "Additive effects"
  txt_additive_model_variables <<- "Variable additive model"
  txt_add_of_cols <<- "add columns"
  txt_add_of_specific_value <<- "addition of a specific value"
  txt_adequation_adjustement_indexes <<- "Adquest and adjustment indices"
  txt_adequation_measurement_of_matrix <<- "Measurement of the matrix"
  txt_adequation_measures <<- "Adequation measures"
  txt_adequation_outside_diagonal <<- "Adequation based on values outside the diagonal"
  txt_adjusted_data_loftus_masson <<- "Adjusted data (Loftus & Masson, 1994)"
  txt_adjusted_means_graph <<- "Adjusted-Graphic Averages"
  txt_adjusted_means <<- "Adjusted Averages"
  txt_adjustement_measure <<- "Adjustment measures"
  txt_adjusted_p_dot_value <<- "Adjusted p value"
  txt_agreement <<- "Agreement"
  txt_aic_criterion <<- "AIC - Akaike Information criteria"
  txt_alpha_warning <<- "Alpha warning"
  txt_alternative <<- "alternative"
  txt_analysis_factor_component <<- "factor and component analyses"
  txt_analysis_on <<- "analysis on"
  txt_analysis_on_truncated_means <<- "Analysis on truncated means"
  txt_analysis_on_variable <<- "Analysis on the variable"
  txt_analysis_premature_abortion <<- "Premature stop of analysis"
  txt_ancova_application_conditions <<- "Terms of application of the ancova"
  txt_and_the_number_of_obs <<- "and the number of observations ="
  txt_and_YZ <<- "and YZ ="
  txt_anova_ancova <<- "variance and covariance analysis"
  txt_anova <<- "Anova"
  txt_anova_on <<- "anova on"
  txt_anova_on_modified_huber_estimator <<- "Anova on Huber's Modified Localization Estimator"
  txt_anova_on_truncated_means <<- "Anova based on truncated averages"
  txt_anova_with_welch_correction <<- "Anova with Welch correction for heterogene variances"
  txt_apparied_correlations <<- "correlations paired"
  txt_apriori <<- "a priori"
  txt_autocorrelation <<- "Autocorrection"
  txt_backward <<- "Backward"
  txt_backward_step_descending <<- "Backward- not-has-not descending"
  txt_barlett_test <<- "Barlett Test"
  txt_bayes_factor_10 <<- "Bayes Factor (10)"
  txt_bayes_factor <<- "BayesFactor"
  txt_bayesian_approach_hierarchical_models <<- "Bayesian approach of hierarchical models"
  txt_bayesian_factor_by_group <<- "Baysian actor by group"
  txt_bayesian_factor <<- "Baysian reactor"
  txt_bayesian_factor_of_model <<- "Model FB"
  txt_bayesian_factors_10 <<- "Bayesian reactor 10"
  txt_bayesian_factors_compute_null_with_bayesian_approach <<- "Bayesian factors: calculates the equivalent of the null hypothesis test by adopting a Bayesian approach. "
  txt_bayesian_factors_for_BP <<- "Bayesian forces for Bravais-Pearson correlation"
  txt_bayesian_factors_for_spearman <<- "Bayesian forces for Spearman correlation"
  txt_bayesian_factors_sequential <<- "Sequential Bayesian Factors"
  txt_bca_bootstrap_on_m_estimator <<- "Bootstrap BCa type on the M-estimetor"
  txt_beta_table <<- "Beta table"
  txt_between <<- "between"
  txt_bidirectionnal <<- "Bidirectional"
  txt_b_m_estimator <<- "b (M estimator)"
  txt_bootstrap_on_BP <<- "Bootstrap on the Bravais Pearson correlation"
  txt_bootstrap_t_method <<- "bootstrap-t method"
  txt_bootstrap_t_method_on_truncated_means <<- "Bootstrap using t method on truncated averages"
  txt_BP_correlation_by_group <<- "Bravais-Pearson group correction"
  txt_breusch_pagan_test <<- "Verification of the non-constency of the error variance (Breusch-Pagan test)"
  txt_cancel <<- "cancel"
  txt_cauchy_prior_width <<- "Cauchy Prior With (r)"
  txt_center_or_center_reduce <<- "Center / center reduce"
  txt_center_reduce <<- "center reduce"
  txt_ceres_graph_linearity <<- "Character of Ceres Testing Linearitis"
  txt_chi_adjustement <<- "Adjustment"
  txt_chi_independance <<- "Independence"
  txt_chi_results_between_var_x <<- "Results of chi.two between variable"
  txt_chi_squared <<- "chi two"
  txt_chi_squared_empirical <<- "chi square empirical"
  txt_chi_squared_likelihood_max <<- "chi square of the maximum likelihood"
  txt_chi_squared_null_model <<- "chi square of model null"
  txt_chi_squared_type <<- "Khi type two"
  #txt_choice <<- "choice"
  txt_coeff_table <<- "Table of coefficients"
  txt_col_correspoding_to_variable <<- "Columns corresponding to the variable"
  txt_col_mean <<- "mean columns"
  txt_cols <<- "columns"
  txt_col_separator <<- "Column Separator"
  txt_cols_in_repeated_measure <<- "Columns in Repeated Measures"
  txt_cols_multiplication <<- "column multiplication"
  txt_comma <<- "virgulate"
  txt_compare_to_baseline <<- "Comparison with a base line"
  txt_compare_two_correlations <<- "Comparison of two correlations"
  txt_comparison_of_two_correlations <<- "comparison of the two correlations"
  txt_comparison_on_truncated_means <<- "Comparison based on truncated averages"
  txt_comparisons_XY <<- "Comparison of XY="
  txt_comparison_to_norm <<- "Comparison with a Standard"
  txt_comparison_two_by_two <<- "Comparison 2 to 2"
  txt_compile_report <<- "generate a report"
  txt_complementary_results <<- "Complementary results (e.g. interaction contrasts and adjusted averages)"
  txt_complete_dataset <<- "Complete data"
  txt_complete_model <<- "Complete Model"
  txt_complexity <<- "complexity"
  txt_complex_model <<- "complex model"
  txt_confidance_threshold <<- "Confidence threshold (1- alpha)"
  txt_confidence_interval_estimated_by_bootstrap <<- "Interval of trust estimates by bootstrap"
  txt_confidence_interval <<- "Confidential Interval"
  txt_confidence_interval_inferior_limit  <<- "Lower bound CI"
  txt_confidence_interval_superior_limit<<- "Upper bound CI"
  txt_confidence_interval_of_saturations_on_bootstrap <<- "Interval of confidence of saturations on the basis of bootstrap - may be biased in presence of Heyhood case"
  txt_confidence_interval_on_bootstrap <<- "Trust interval based on bootstrap"
  txt_confidence_interval_on_standard_error <<- "Confidence interval based on standard alpha error"
  txt_confirmatory_factorial_analysis <<- " confirmatory factor analysis"
  txt_contrast <<- "contrast"
  txt_contrasts <<- "contrasts"
  txt_contrasts_for <<- "Contrasts for"
  txt_contrasts_table_imitating_commercial_softwares <<- "Table of contrasts imitating commercial software"
  txt_contrasts_table <<- "Contrast table"
  txt_control_variables <<- "Variable-s to control"
  txt_correction_for_polyc_corr_must_be_between_zero_and_one <<- "The correction for the calculation of polycoric correlations shall be between 0 and 1."
  txt_correlation_between_scores_and_factors <<- "Correlations of scores with factors"
  txt_correlation_between_var_x <<- "Correlation between variable"
  txt_correlation_is <<- "correction"
  txt_correlation_matrix_determinant <<- "Determining the correlation matrix"
  txt_correlation_matrix_determinant_information <<- "Determining the correlation matrix: information"
  txt_correlations_between_factors <<- "correlations between factors"
  txt_correlations_comparison <<- "comparison of correlations"
  txt_correlations_matrix_afe <<- "Correlation matrix used for AFE"
  txt_covariance_matrix_adjusted <<- "Adjusted covariance matrix"
  txt_covariance_matrix_estimated <<- "Estimated covariance matrix"
  txt_cox_snell_r_2 <<- "Cox and Snell R^2"
  txt_cronbach_alpha <<- "Cronbach Alpha"
  txt_cronbach_alpha_on_whole_scale <<- "Cronbach Alpha on Scale Totalite"
  txt_cross_validation <<- "Validation crossee"
  txt_csv_file <<- "CSV file"
  txt_cumulated_explaination_ratio <<- "Cumulative share of explanation"
  txt_cumulated_explained_variance_ratio <<- "proportion of variance explained cumulated"
  txt_dataframe_choice <<- "Dataframe selection"
  txt_data_import_export_save <<- "Data - (Import, export, backup)"
  txt_decimal_separator <<- "Separator of decimals"
  txt_default_outputs <<- "Releases by default"
  txt_delete_observations_with_missing_values <<- "Deletion of observations with missing values"
  txt_denominator <<- "Denominator"
  txt_dependant_variables <<- "Variable-dependent-s"
  txt_dependant_variable <<- "dependent variable"
  txt_descriptive_statistics_by_group <<- "Descriptive statistics by group"
  txt_detailed_corr_analysis <<- "Analysis desize (Bravais Pearson/Spearman/tau) for one or few correlations"
  txt_deviation <<- "Deviance"
  txt_dichotomic_ordinal <<- "dichotomics/ordinal"
  txt_difference <<- "Difference"
  txt_distance_mediation_effect <<- "Remote mediation effect"
  txt_distance_mediator <<- "Mediation distance"
  txt_do_nothing_keep_all_obs <<- "Do nothing - Keep all observations"
  txt_dot <<- "point"
  txt_durbin_watson_test_autocorr <<- "Durbin-Watson test - autocorrelations"
  txt_dw_statistic <<- "D-W statistics"
  txt_dynamic_crossed_table <<- "Dynamic Cross Table"
  txt_effect <<- "Effect"
  txt_equals_to <<- "egal a"
  txt_error <<- "error"
  txt_estimated_parameters_not_standardized <<- "Non-standardized Parameters"
  txt_estimated_parameters <<- "Advised parameters"
  txt_estimated_parameters_standardized <<- "Standardized estimated parameters"
  txt_estimation <<- "estimate"
  txt_excel_file <<- " Excel file"
  txt_exogenous_fixed_variables <<- "Variables exogenes fixed [fixed.x=default]"
  txt_expected <<- "Attended"
  txt_expected_sample <<- "Expected effects"
  txt_experimental_pan_between <<- "Pan experimental enters"
  txt_explaination_ratio <<- "Proportion of explanation"
  txt_explained_variance_ratio <<- "proportion of variance explained"
  txt_explained_variance <<- "Variance explained"
  txt_exponant <<- "exposant"
  txt_exponant_or_root <<- "exposant or root"
  txt_exponential <<- "exponential"
  txt_export_data <<- "export data"
  txt_factorial_analysis <<- "factorial analysis"
  txt_factorial_analysis_using_fa_with_method <<- "factorial analysis using the fa function of the psych package with the method"
  txt_factorial_exploratory_analysis <<- "Exploratory factor analysis"
  txt_factor_name <<- "factor name"
  txt_factors <<- "factors. "
  txt_factors_ortho <<- "Orthogonality of factors [orthogonal=FALSE]"
  txt_factors_to_keep_accord_to_parallel_analysis_is <<- "the number of factors to remember according to the parallel analysis is"
  txt_fiability_analysis <<- "Analysis of reliability and agreement"
  txt_fiability_by_removed_item <<- "reliability by item deletes"
  txt_for_a_detailed_results_description_distal <<- "For a detailed description of the results, ?distal.med"
  txt_for_a_detailed_results_description_mediation <<- "For a detailed description of the results, ?mediation"
  txt_forward_step_ascending <<- "Forward - not-a-not ascending"
  txt_friedman_anova_pairwise_comparison <<- "Comparison 2 to 2 for Friedman's ANOVA"
  txt_f_value <<- "F value"
  txt_get_working_dir <<- "get work directory"
  txt_global_model_estimation <<- "Global Model Estimation"
  txt_graphic_mean_sd <<- "Graphic representation - Medium and level-type"
  txt_graphics <<- "Graphics"
  txt_graphics_informations <<- "Information on graphics"
  txt_group_analysis <<- "Group Analysis"
  txt_groups_analysis <<- "group analysis"
  txt_groups_variables <<- "Variable-s groups"
  txt_grubbs_test <<- " Grubbs Test"
  txt_hierarchical_factorial_analysis <<- "Hierarchical factor analysis"
  txt_hierarchical_model_analysis <<- "Hierarchical model analysis"
  txt_hierarchical_models_complete_model_sig_at_each_step <<- "Hierarchical models - significativite of the complete model to each step"
  txt_hierarchical_models_deviance_table <<- "Table of the analysis of the deviance of hierarchical models"
  txt_hierarchical_models <<- "hierarchical models"
  txt_hierarchical_models_variance_analysis_table <<- "Table of variance analysis of hierarchical models"
  txt_hosmer_lemeshow_r_2 <<- "Hosmer and Lemeshow R^2"
  txt_hypergeom_total_sample_fixed_rows_cols <<- "hypergeom - Total fixed strength for rows and columns"
  txt_hypothesis_analysis <<- "Analysis - Hypothesis tests"
  txt_identified_outliers_synthesis <<- "Synthesis of the number of observations considered to be influential"
  txt_identifying_outliers <<- "Identification of influential values"
  txt_id_variable <<- "Variable *Identifier*"
  txt_import_data <<- "import data"
  txt_imput_missing_values <<- "Impacting Missing Values"
  txt_independant_correlations <<- "Independent adjustments"
  txt_independant_group_variables <<- "Variables to independent groups"
  txt_independant_variable <<- "Independent variable"
  txt_indepmulti_fixed_sample_rows_cols <<- "indepMulti - Fixed number for columns - variable"
  txt_indepmulti_total_fixed_rows_cols <<- "indepMulti - Total fixed strength for lines - variable"
  txt_inferior <<- "Inner"
  txt_inferior_or_equal_to <<- "inferior or equal"
  txt_inferior_proba <<- "inferior probability"
  txt_inferior_to <<- "under a"
  txt_inflation_variance_factor <<- "Inflation factor of variance"
  txt_influence_method <<- "Influence Measurement"
  txt_information <<- "Information"
  txt_init_values <<- "Departure values"
  txt_inspect_initial_values <<- "Inspect start values"
  txt_inspect_model_matrices <<- "Inspect model matrices"
  txt_inspect_model_representation <<- "Inspect model representation"
  txt_interaction_effects <<- "Interaction effects"
  txt_interactive_model_variables <<- "Interactive models"
  txt_is_different_from <<- "is different from"
  txt_jointmulti_total_fixed_sample <<- "jointMulti - Total fixed staff"
  txt_judge1 <<- "Juge 1"
  txt_judge2 <<- "Juge 2"
  txt_kaiser_meyer_olkin_index <<- "Kaiser-Meyer-Olkin global index"
  txt_keep_default_values <<- "Keep values by default"
  txt_kendall_coeff <<- "Kendall Match Coefficient"
  txt_kendall_partial_semipartial_tau <<- "Kendall partial/semipartial"
  txt_kendall_partial_tau <<- "Kendall partial rate"
  txt_kendall_semipartial_tau <<- "Kendall Semi-Partial"
  txt_kendall_tau <<- "Kendall Tau"
  txt_kolmogorov_smirnov_comparing_two_distrib <<- "Kolmogorov-Smirnov test comparing two distributions"
  txt_labeled_outliers <<- "Values considered influential"
  txt_latent_variable_name <<- "Latent variable name"
  txt_less_square_diagonally_pondered <<- "mind square weight diagonally"
  txt_less_square_generalized <<- "mind tile generalises"
  txt_less_square_not_pondered <<- "mind unweighted square"
  txt_less_square_pondered <<- "mind square"
  txt_levene_test_verifying_homogeneity_variances <<- "Levene test checking variance homogeneity"
  txt_likelihood_only_for_estimator <<- "True (only for estimator=ML) [likelihood=default]"
  txt_likelihood_ratio_g_test <<- "Ratio of likelihood (G test)"
  txt_lilliefors_d <<- "D de Lilliefors"
  txt_linearity_graph_between_predictors_and_dependant_variable <<- "Character testing linearite between predictors and dependent variable"
  txt_link_only_for_estimator <<- "Link (only for estimator=MML) [link=probit]"
  txt_list_of_objects_in_mem <<- "list of objects in memory"
  txt_logarithm <<- "logarithm"
  txt_long_or_large_format <<- "Long format wide format"
  txt_lower_bound_rmsea <<- "inferior limit of RMSEA"
  txt_mann_whitney_test <<- " Mann-Whitney test - Wilcoxon"
  txt_mathematical_operations_on_variables <<- "Mathematic operations on variables"
  txt_matrix_type <<- "matrix type"
  txt_max_likelihood_chi_squared_proba_value <<- "value of the probability of the chi carre maximum likelihood"
  txt_max_likelihood <<- "maximum likelihood"
  txt_mcnemar_results_between_var_x <<- "Results of McNemar test between variable"
  txt_mcnemar_test <<- "McNemar Test"
  txt_mcnemar_test_with_continuity_correction <<- "McNemar test with continuity correction"
  txt_mcnemar_test_without_yates_correction <<- "McNemar test without continuity correction"
  txt_mcnemar_test_with_yates_correction <<- "McNemar Test with Yates Correction"
  txt_mean1 <<- "Average1"
  txt_mean2 <<- "Average2"
  txt_mean_complexity <<- "Medium Complexity"
  txt_mean_complexity_is <<- "average complexity is of"
  txt_means_adjusted_standard_errors <<- "adjusted averages and standard errors"
  txt_means_comparison <<- "Comparison of Averages"
  txt_mean_sd_for_adjusted_data <<- "Average and scale-type for adjusted data"
  txt_mean_sd_for_non_adjusted_data <<- "Average and scale-type for unadjusted data"
  txt_mean_sd <<- "Average and scale-type"
  txt_measured_variable_name <<- "Measuring variable name"
  txt_median <<- "Mediane"
  txt_mediation_effect <<- "Mediation Effects"
  txt_mediator2 <<- "Mediator 2"
  txt_mediator <<- "Mediator"
  txt_method_choice <<- "Choice of the method"
  txt_min_correlation_between_scores_and_factors <<- "Minimum possible correlation of scores with factors"
  txt_minus <<- "less"
  txt_missing_values_treatment <<- "Treatment of Missing Values"
  txt_mixt_correlations <<- "mixed correlations"
  txt_modalities_name_for <<- "Names of the modes for"
  txt_modalities_to_regroup <<- "Modalites to group"
  txt_modality <<- "modality"
  txt_model_degrees_of_freedom <<- "degrees of model freedom"
  txt_model_matrix <<- "Model Matrix"
  txt_model_representation <<- "Model representation"
  txt_model_significance <<- "Significativite of the global model"
  txt_multicolinearity_tests <<- "Multicolinearite tests"
  txt_multicolinearity_test <<- "Multicolinearite test"
  txt_multiple_imputation_amelia <<- "Multiple imputation - Amelia"
  txt_multiple_r_square_of_factors_scores <<- "R multiple square scores with factors"
  txt_multiplication <<- "multiplication"
  txt_multivariate_normality <<- "Normalite multivarie"
  txt_nb_variables_measured <<- "Number of variables measured"
  txt_negative_values <<- "negative values"
  txt_new_data_set <<- "new data set"
  txt_new_dir <<- "new directory"
  txt_N_of_XY_corr <<- "XY correlation N"
  txt_N_of_XY_NUM_corr <<- "N of XY:TXT"
  txt_N_of_XZ_corr <<- "N of XZ correlation"
  txt_N_of_XZ_NUM_corr <<- "N of XZ:TXT"
  txt_non_adjusted_data <<- "Unadjusted data"
  txt_non_centered <<- "No center"
  txt_no <<- "no"
  txt_non_parametric_test <<- "Nonparametric test"
  txt_non_param_model <<- "Non-parametric model"
  txt_non_param_test <<- "non-parametric test"
  txt_non_pondered_coeff <<- "Kappa coefficient non-weight"
  txt_non_standardized_residuals <<- "Non-standardised residues"
  txt_null_hypothesis_tests <<- "H0 test"
  txt_null_model_degrees_of_freedom <<- "Degrees of null model freedom"
  txt_numerator <<- "Numerator"
  txt_objective_function_of_model <<- "objective model function"
  txt_objective_function_of_null_model <<- "objective null model function"
  txt_objects_in_mem <<- "Memory objects"
  txt_object_to_remove <<- "Objects to be deleted"
  txt_observed <<- "Observations"
  txt_observed_sample <<- "Observed Effects"
  txt_odd_ratio <<- "Odd ratio"
  txt_order <<- "Sort"
  txt_orthogonals_inverse <<- "orthogonal reverses"
  txt_orthogonals <<- "orthogonal"
  txt_other_correlations <<- "Other correlations"
  txt_other_data <<- "other data"
  txt_outliers <<- "Influential observations"
  txt_outliers_synthesis <<- "Synthesis of influential observations"
  txt_outliers_values <<- "Influential values"
  txt_packages_install <<- "Installation of packages"
  txt_packages_update <<- "packages update"
  txt_packages_verification <<- "Verification of packages"
  txt_parallel_analysis <<- "parallel analyses"
  txt_param_model <<- "parametric model"
  txt_param_tests <<- "Parametric tests"
  txt_param_test <<- "parametric test"
  txt_partial_and_semi_correlations <<- "Partial and semi-partial corrections"
  txt_partial_corr_BP_by_group <<- "Partial correction of Bravais-Pearson by group"
  txt_partial_correlations_matrix <<- "Partial Correlations Matrix"
  txt_partial_rho <<- "Rho partiale de Spearman"
  txt_partial_semi_BP <<- "Partial/semi-partial correction of Bravais Pearson"
  txt_partial_semi_partial_rho <<- "Partial/Semipartial Rho"
  txt_partial_spearman_by_group <<- "Partial patch of Spearman by group"
  txt_participants_id <<- "participating identifier"
  txt_partila_correlations <<- "Partial corrections"
  txt_percentage_col <<- "Percentage by column"
  txt_percentage_row <<- "Percentage per line"
  txt_percentage_total <<- "Total percentage"
  txt_percentile_bootstrap_on_m_estimators <<- "Percentile bootstrap on M-estimetor"
  txt_p_estimation_with_monter_carlo <<- "Value estimated by Monte Carlo simulation"
  txt_plus <<- "plus"
  txt_poisson_total_not_fixed_sample <<- "fish - total non-fixed"
  txt_polyc_correlations <<- "polychoric correlations"
  txt_polynomials <<- "polynomials"
  txt_pondered_kappa <<- "Kappa weight coefficient"
  txt_positive_values <<- "positive values"
  txt_predicted_probabilities <<- "Probability"
  txt_predictor <<- "Predictor"
  txt_principal_analysis <<- "Main Analysis"
  txt_principal_analysis_using_psych_with_algo <<- "main component analysis using the [principal] function of the psych package, the algorithm is"
  txt_principal_component_analysis <<- "Main Component Analysis"
  txt_probabilities <<- "probabilities"
  txt_probability_matrix <<- "probability matrix"
  txt_probability_value <<- "probability value"
  txt_proper_values_index <<- "Index of own values"
  txt_pseudo_r_square_delta <<- "Delta du pseudo R carre"
  txt_p_value_with_monte_carlo <<- "Value p by Monte Carlo simulation"
  txt_ranks_lower <<- "ranges"
  txt_ranks_upper <<- "Rangs"
  txt_references <<- "References"
  txt_remove_object_in_memory <<- "Deletion of memory object"
  txt_replace_by_mean <<- "Replace by Average"
  txt_replace_by_median <<- "Replace with media"
  txt_residual_distribution <<- "Distribution of residual"
  txt_residual_error <<- "Residual error"
  txt_residual <<- "residual"
  txt_residuals_distribution <<- "Distribution of survivors"
  txt_residue <<- "Residus"
  txt_residues_significativity_holm_correction <<- "Significativite des residus - probability corrected by applying the Holm method"
  txt_residue_standardized_adjusted <<- "Residues standardises fit"
  txt_residue_standardized <<- "Residue standardized"
  txt_result <<- "Result"
  txt_rho <<- "Rho de Spearman"
  txt_robust_analysis <<- "Sturdy analyses"
  txt_robusts <<- "robust"
  txt_robusts_statistics <<- "Strudy statistics"
  txt_robust_statistics <<- "Strudy statistics - can take time"
  txt_robusts_tests_with_bootstraps <<- "Sturdy test - involving bootstraps"
  txt_rotation_is_a_rotation <<- "rotation is a rotation"
  txt_sample_size_NUM <<- "Size of sample:TXT"
  txt_saturations_sum_of_squares <<- "Sum of squares of saturations"
  txt_search_for_new_function <<- "Search for a new function"
  txt_second_variables_set <<- "Second set of variables"
  txt_selected_data <<- "Give that you just selected"
  txt_selection_method_akaike <<- "Selection method - Akaike information criteria"
  txt_selection_method_bayesian_factor <<- "Selection methods: Bayesian factors"
  txt_selection_method <<- "Selection method"
  txt_selection_methods <<- "Selection methods"
  txt_selection <<- "selection"
  txt_select_obs <<- "Select Observations"
  txt_select_variables <<- "Select variables"
  txt_semi_BP <<- "Semi-partial correction of Bravais Pearson"
  txt_semicolon <<- "point comma"
  txt_semi_partial_rho <<- "Spearman Semi-Partial Rho"
  txt_sequential_bayesian_factors_robustness_analysis <<- "Sequential Bayesian Factors - Robustness Analysis"
  txt_shapiro_wilk <<- "W de Shapiro-Wilk"
  txt_simple_mediation_effect <<- "simple mediation effects"
  txt_slopes_homogeneity_between_groups_on_dependant_variable <<- "Test of homogeneite slopes between groups on the dependent variable"
  txt_spearman_kendall_corr_by_group <<- "Spearman/Kendall group correction"
  txt_specific_val_multiplication <<- "multiplication of a specific value"
  txt_specify_contrasts <<- "specify your contrasts"
  txt_specify_model <<- "Specify the model"
  txt_specify_working_dir <<- "specify work directory"
  txt_spss_file <<- "SPSS file"
  txt_square <<- "square"
  txt_rectangular <<- "rectangular"
  txt_standardized_parameters <<- "Standardized Parameters"
  txt_statistic <<- "statistic"
  txt_step <<- "etape"
  txt_student_bootstrap_on_truncated_means <<- "Student bootstrap on truncated means"
  txt_student_t_by_group <<- "Student t by group"
  txt_student_t_independant <<- "tstudent for independent samples"
  txt_student_t <<- "Student t"
  txt_student_t_test_norm <<- "Student test - comparison to a standard"
  txt_student_t_test_paired <<- "Student test - comparison of two matching samples"
  txt_substraction <<- "subtraction"
  txt_sufficient_factors <<- "sufficient factors"
  txt_superior_or_equal_to <<- "upper or equal a"
  txt_superior_proba <<- "high probability"
  txt_superior <<- "Superior"
  txt_superior_to <<- "upper a"
  txt_supports_alternative <<- "In favour of alternative hypothesis"
  txt_supports_null <<- "In favour of null hypothesis"
  txt_suppress_all_outliers <<- "Deleting all outliers"
  txt_suppress_outliers_manually <<- "Manual Deletion"
  txt_synthesis_table <<- "Summary Table"
  txt_teaching_material <<- "Pedagogical material"
  txt_tetra_polyc_corr_matrix_or_mixt <<- "Tetrachoric/polychoric or mixed correlation matrix"
  txt_this_tests_if <<- "It tests if"
  txt_threshold <<- "Threshold"
  txt_time_1 <<- "time 1"
  txt_time1 <<- "time1"
  txt_time_2 <<- "time 2"
  txt_time2 <<- "time2"
  txt_tolerance <<- "Tolerance"
  txt_total_sample_not_fixed <<- "Total non-fixed effect"
  txt_troncature_num <<- "Troncature:TXT"
  txt_truncated_means <<- "Truncated averages"
  txt_t_test_choice <<- "Test selection t"
  txt_tucker_lewis_fiability_factor <<- "Tucker Lewis reliability factor - TLI"
  txt_two_independant_samples <<- "Two independent samples"
  txt_two_paired_samples <<- "Two paired samples"
  txt_txt_file <<- "Txt file"
  txt_type <<- "Type"
  txt_understanding_alpha_and_power <<- "Understanding Alpha and Power"
  txt_understanding_bayesian_inference <<- "Understanding a Bayesian Inference"
  txt_understanding_central_limit_theorem <<- "Understanding the central theorem limit"
  txt_understanding_confidance_interval <<- "Understanding a confidence interval"
  txt_understanding_corr_2 <<- "Understanding a correlation 2"
  txt_understanding_corr <<- "Understanding correlation"
  txt_understanding_heterogenous_variance_effects <<- "Understanding the effects of heterogene variances"
  txt_understanding_likelihood <<- "Understanding the maximum likelihood"
  txt_understanding_negative_positive_predic_power <<- "Understanding positive predictive power and negative predictive power"
  txt_understanding_prev_sens_specificity_2 <<- "Understanding Prevalence, Sensibility and Specificity 2"
  txt_understanding_prev_sens_specificity <<- "Understanding prevalence, sensitivity and specificity"
  txt_upper_bound_rmsea <<- "the upper limit of the RMSEA"
  txt_user_exited_easieR <<- "You left easieR"
  txt_values <<- "values"
  txt_value <<- "value"
  txt_variable_descriptive_statistics <<- "Descriptive variable statistics"
  txt_variables_coeff_matrix <<- "variable coefficient matrix"
  txt_variables_contribution_to_model <<- "Contribution of variables to the model"
  txt_variables_from_step <<- "Variable of this step"
  txt_verify_packages_install <<- "Check package installation"
  txt_view_data <<- "see data"
  txt_VIF<<-"VIF"
  txt_warning <<- "Warning"
  txt_wilcoxon_by_group <<- "Wilcoxon by group"
  txt_without_outliers <<- "Data without influential value"
  txt_without_welch_correction <<- "without Welch correction"
  txt_without_yates_correction <<- "Without Yates Correction"
  txt_with_welch_correction <<- "with Welch correction"
  txt_with_yates_correction <<- "With Yates Correction"
  txt_working_dir <<- "Work Directory"
  txt_x_axis_variables <<- "Variable-s in abscess"
  txt_XY_correlation <<- "Correlation between XY"
  txt_XY_NUM_correlation <<- "Correlation between XY:TXT"
  txt_XZ_correlation <<- "Correlation between XZ"
  txt_XZ_NUM_correlation <<- "Correlation between XZ:TXT"
  txt_y_axis_variables <<- "Variable-s ordered"
  txt_yes <<- "yes"
  txt_your_data <<- "Your data"
  txt_YZ_correlation <<- "Correlation between YZ"
  txt_YZ_NUM_correlation <<- "Correlation between YZ:TXT"
  ask_probability_correction <<- "Which p adjustment do you want ? If you do not want any p adjustment, choose +none+"
  ask_contrasts_must_be_ortho <<- "The contrasts must be orthogonal. Do you want to continue?"
  desc_bayesian_factors_chosen_in <<- "Baysian factors is choosen in "
  desc_cross_validation_issues <<- "cross validation is encountering some issues"
  desc_easier_metapackage <<- "easieR: An R metapackage. Retrieved from https://github.com/NicolasStefaniak/easieR"
  desc_first_time_easier <<- " If you are using easieR for the first time, please use the function ez.install in order to ensure that easieR will work properly.n If you are using easieR for the first time, please use the ez.install function to ensure that easieR works properly."
  ask_chose_variables <<- "please choose the variable(s)"
  ask_correlations_type <<- "Type of correlations?"
  ask_dependant_variable_name <<- "What is the name of the dependent variable?"
  ask_factors_number <<- "Number of factors?"
  ask_filename <<- "What name do you want to give the file?"
  ask_independant_variable_name <<- "What is the name of the independent variable?"
  ask_is_long_format_correct <<- "Is the structure in a long format of your data correct?"
  ask_model <<- "Model?"
  ask_ordinal_variables <<- "Ordinal Variables?"
  ask_save_results <<- "Save Results?"
  ask_save <<- "Do you want to save?"
  ask_specify_contrasts <<- "Please specify contrasts. "
  ask_variables <<- "What are the variables to select?"
  ask_variables_type <<- "Nature of variables?"
  ask_what_to_do <<- "What do you want to do?"
  ask_which_analysis <<- "What analysis do you want?"
  desc_all_contrasts_description <<- "The a priori contrasts correspond to the contrasts that allow to test hypotheses a priori.nThe contrasts 2 to 2 allow to make all comparisons 2 to 2 by applying or not a correction to probabilities"
  desc_contrasts_must_be_coeff_matrices_in_list <<- "Contracts must be matrix coefficients placed in a list whose name of each level corresponds to a factor"
  desc_percentage_outliers <<- "% of observations considered influential"
  desc_robusts_statistics_could_not_be_computed_verify_WRS <<- "The robust statistics could not be achieved. Check the installation of the WRS package"
  desc_some_participants_have_missing_values_on_repeated_measures <<- "Some participants have missing values on the repeted measurement factors. They will be removed from the analyses."
  txt_absence_of_difference_between_groups_test_on <<- "Test of absence of difference between groups on "
  txt_anova_on_medians <<- "Anova on the media"
  txt_anova_on_m_estimator <<- "ANOVA on M estimator"
  txt_bayesian_factors <<- "Baysian Factors"
  txt_BP_correlation <<- "Bravais-Pearson Correlation"
  txt_center <<- "center"
  txt_cohen_d <<- "D of Cohen"
  txt_correlations <<- "Correlations"
  txt_correlations_matrix <<- "Correlations Matrix"
  txt_descriptive_statistics_of_interaction_between_x <<- "Descriptive statistics of the interaction between"
  txt_descriptive_statistics <<- "Descriptive statistics"
  txt_empirical_chi_square_proba_value <<- "value of the probabilities of empirical chi tile"
  txt_factor <<- "factor."
  txt_friedman_anova <<- "Anova de Friedman"
  txt_import_results <<- "import results"
  txt_interface_objects_in_memory <<- "Interface - objects in memory, clean memory, working directory, language"
  txt_intraclass_correlation <<- "Intraclass correlation"
  txt_kruskal_wallis_pairwise <<- "Kruskal-Wallis Test - Comparison Two to Two"
  txt_kruskal_wallis_test <<- "Kruskal-Wallis Test"
  txt_latent_variables_intercept <<- "Intercept of latent variables [int.lv.free=FALSE]"
  txt_observed_variables_intercept <<- "Intercept of observed variables [int.ov.free=FALSE]"
  txt_logistic_regressions <<- "Logistical Regressions"
  txt_mauchly_test_sphericity_covariance_matrix <<- "Mauchly test testing the sphericite of the covariance matrix"
  txt_none <<- "none"
  txt_non_param_analysis <<- "Nonparametric analysis"
  txt_normality_tests <<- "Standardity test"
  txt_pairwise_comparisons <<- "Comparations 2 to 2"
  txt_pairwise <<- "pairwise"
  txt_partial_corr_BP <<- "Partial correction of Bravais-Pearson"
  txt_preprocess_sort_select_operations <<- "Pretreatments (tri, selection, mathematical operations, Missing value processing)"
  txt_press_enter_to_continue <<- "Press [enter] to continue"
  txt_regressions <<- "regressions"
  txt_repeated_measures <<- "Measures repeats"
  txt_sample_size <<- "size of sample"
  txt_test_model <<- "Test model"
  txt_variables <<- "variables"
  txt_variable <<- "variable"
  desc_corr_group_analysis_spec <<- "If you want to perform the analysis for different subsamples based on a categorical criterion (i.e.; perform a group analysis) \n choose yes. In this case, the analysis is done on the complete sample and on the subsamples. \n If you want the analysis for the complete sample only, choose no. The group analysis does not apply to robust statistics."
  desc_outliers_removal_implications <<- "Delete all outliers removes all values beyond p(chi.two)< 0.001. Delete one observation at a time makes it possible to make a detailed analysis of each observation considered to be influential from the most extreme value. The procedure stops when no more observations are considered influential"
  txt_bilateral <<- "Bilateral"
  desc_no_compatible_object_in_mem_for_aov <<- "there is no object compatible with aov.plus in the memory of R. You must make an analysis of variance to the prerequisite"
  desc_this_function_means_and_sd_adjusted_interaction_effect_possible <<- "This function provides the adjusted averages and standard errors as well as the corresponding graph. With the post hoc choice on interactions, you can test the interaction effects 2 a 2 and the simple effects. "
  txt_anova_plus <<- "Anova plus"
  desc_center_and_center_reduce_explaination <<- "Center allows you to have a zero average by keeping the chart-type. Centrer reduce corresponds to the formula of z. The average is 0 and the standard scale is 1. The lower probability corresponds to the probability of having a lower or equal z. The higher probability corresponds to the probability of having a higher or equal z"
  desc_proba_sum_is_not_one_or_not_enough_proba <<- "The sum of probabilities is different from 1 or the number of probabilities does not correspond to the number of modes of the variable. Please enter a valid probability vector"
  desc_if_non_fixed_sample_poisson_law <<- "If the total number is not fixed, it is hypothesized that the observations occur according to a fish law. Distribution on the levels of a factor occurs with a fixed probability. Distribution is a fish distribution"
  desc_distribution_is_joint_multinomial <<- "The option *Fixed total effect* must be chosen if the null hypothesis is made that the distribution in each of the cells in the table is fixed. Distribution is a multinomial distribution attached"
  desc_distribution_is_independant_multinomial <<- "The fixed total number option for lines* must be chosen if the number of staff for each line is the same, as if you want to ensure a matching between groups. Distribution is an independent multinomial distribution"
  desc_corr_detailed_analysis <<- "the size analysis allows to have descriptive statistics, normalite tests, the cloud of points, \n robust statistics, all correlation coefficients. \n the correlation matrix allows to control the error of 1e species and is adapted for a large number of correlations \n the correlation comparison allows to compare 2 dependent or independent correlations \n The choice + other correlations + allows to have the tetrachoric and polychoric correlation"
  desc_corr_values_must_be_between_min_1_and_1 <<- "The correlation values must be between -1 and 1/n and the numbers must be positive integers"
  desc_you_can_choose_contrasts_you_want <<- "You can choose the contrasts you want. Nevertheless, the rules concerning the application of contrasts must be respected. Contrasts can be specified manually. In this case, please select the contrasts"
  desc_square_matrix_rectangular_matrix <<- "A square matrix is a matrix with all Correlations 2 to 2. A rectangular matrix is a matrix in which a first set of variables is correlated with a second set of variables."
  desc_complete_dataset_vs_identification_outliers_vs_without_outliers <<- "the complete data represent the classical analysis on all usable data, the identification of the influential values allows to identify the observations which are considered statistically to influence the results. data analysis without influential values performs analysis after removal of influential values. This option stores in the memory of R a new database of data without influential value in an object bearing the name *nettoyees*"
  desc_welcome_in_easieR <<- "Welcome in easieR - For more information, please visit:https://theeasierproject.wordpress.com/"
  ask_variables_type_for_anova <<- "Please specify the type(s) of variable(s) you want to include in the analysis.\nYou can choose several (e.g., for mixed annova or ancova)"
  ask_correction_anova_contrasts <<- "Correction?"
  txt_independant_groups <<- "Independent groups"
  txt_covariables <<- "Covariates"
  txt_cfa_information_default <<- "information [information=default]"
  txt_cfa_continuity_correction_zero_keep_margins_default <<- "correction of continuity [zero.keep.margins=default]"
  txt_cfa_estimator_ml_default <<- "estimator [estimator=ml]"
  txt_cfa_groups_null_default <<- "groups [group=NULL]"
  txt_cfa_test_standard_default <<- "test"
  txt_cfa_standard_error_default <<- "standard error"
  txt_cfa_observed_variabes_standardization_true_default <<- "standardization of observed variables"
  txt_cfa_latent_variables_indicators_estimates_true_default <<- "Estimation of indicators of latent variables [std.lv=FALSE]"
  desc_wls_corresponds_to_adf_plus_explaination_other_estimators <<- "[WLS] corresponds to [ADF]. Estimators with extensions [M],[MV],[MVSF],[R] are robust versions of classic estimators [MV],[WLS], [DWLS], [ULS]"
  ask_observed_variables_intercept_zero <<- "Intercept VO=0?"
  ask_latent_variables_intercept_zero <<- "Intercept VL=0?"
  ask_how_to_treat_exaequo_rank <<- "How do you want to treat ex-aequo? The method *warning* is the average between ex aequo (the most usual), *first* assigns the first ranking ex aequo to the first value in the data, *last* to the last, *min* assigns the minimum value to all ex aequo and *max* the maximum value. "
  desc_for_ordinal_and_dicho_varible_prefer_min_res <<- "For the ordinal and dichomic variables, choose the method of minimum residus - minres - or least weighting squares - wls. For continuous variables, the maximum likelihood if normalite is respected - ml"
  desc_saturation_criterion_show_only_above_threshold <<- "The saturation criterion allows the results table to show only saturation above the fixed threshold"
  desc_to_find_new_analysis_search_in_english <<- "To find a new analysis, it is necessary to do your search in English. You can use several words in the search. A html page containing all the packages referring to the search analysis will open."
  txt_division <<- "division"
  desc_if_you_select_both_operations_value_will_be_added_to_chose_cols <<- "If you select both options at the same time, the specified value will be added to all the selected columns and then the selected columns will be added. To add a specific value to the total, select the column addition option only."
  desc_if_you_select_both_operations_value_will_be_multiplied_to_chose_cols <<- "If you select both options at the same time, the specified value will be multiplied to all the selected columns and then the selected columns will be multiplied among them. To multiply a specific value in total, please select the column multipication option only."
  ask_chose_values_on_left_of_minus_symbol <<- "Please select the values to the left of the symbol *minus*. If several variables are selected, the rules of the matrix calculation are applied. "
  desc_one_or_same_number_cols_on_both_sides_only <<- "There shall be only one column or the number of columns to the right of the symbol *less* shall be equal to the number of columns to the left of the symbol *less*"
  ask_specify_exponant_value <<- "Please specify the value of the exhibitor. NOTE: For roots, the exponent is the inverse value. For example, the square root is equal to 1/2, the cubic root 1/3..."
  desc_expression_must_be_correct_example <<- "The expression must be correct. You can use the variables name directly the operators are +,-,*,/,^,(,). A correct expression would be:"
  ask_chose_relation_between_vars_regressions_log <<- "Please choose the type(s) of relationships between variables. Additive effects take the form of y=X1+X2 while interaction effects take the form of Y=X1+X2+X1:X2"
  ask_variables_order_for_max_likelihood <<- "The order of entry of the variables is important for the calculation of the maximum likelihood. Please specify the order of entry of variables"
  ask_integrate_probabilities_to_dataset <<- "Do you want to integrate probabilities into your database?"
  ask_specify_other_options_regressions <<- "Do you want to specify other options? You can select several. The selection methods allow you to select the best model based on statistical criteria. Hierarchical models allow to compare several models. Cross validations make it possible to check if a model is not dependent on the data. This option is to be used with selection methods. The group analysis makes it possible to achieve the same regression for subgroups. Influence measurements are the other measures usually used to identify influential values. "
  desc_possible_apply_multiple_selection_criterion <<- "It is possible to apply several selection criteria simultaneously, involving or not several variables. Please specify the number of variables you want to apply one or more selection criteria. Please choose the variables on which you should apply a selection"
  desc_skew_and_kurtosis_between_1_and_3 <<- "Type of skew and kurtosis, shall be between 1 and 3:TXT"
  desc_with_two_equal_means_ratio_must_be_5_percent <<- "With two equal averages, or almost equal, the error rate must be 5%. Gradually modify the gap between the scratch-types and see how the alpha error rate will be changed"
  desc_bilateral_superior_inferior_test_t <<- "Bilateral analysis tests the existence of a difference. Superior choice test if average is strictly superior \n The lower choice tests the existence of a strictly inferior difference"
  txt_numeric_variables <<- "Numeric variables"
  txt_select_language <<- "Choose language"
  txt_dot_adjusted <<- ".adjusted"
  txt_bca_inferior_limit <<- "Bca lim inf"
  txt_bca_inferior_limit <<- "Bca.lim.inf"
  txt_bca_superior_limit <<- " Bca.lim.sup"
  txt_bca_superior_limit <<- "Bca lim sup"
  txt_bca_superior_limit <<- "Bca.lim.sup"
  txt_centered_dot_reduced <<- "centered.reduced"
  txt_chi_dot_squared <<- "chi.2"
  txt_chi_dot_squared_model <<- "chi.2.model"
  txt_chi_dot_squared <<- "chi.squared"
  txt_chi_dot_squared <<- "chi.two"
  txt_chi_dot_squared_adjustment <<- "chi.two adjustment"
  txt_pairwise_comparison <<- "pairwaise comparison"
  txt_continuous <<- "continuous"
  txt_greenhouse_geisser_huynn_feldt_correction <<- "Correction : Greenhouse-Geisser &  Hyunh-Feldt"
  txt_df <<- "df"
  txt_df1 <<- "df1"
  txt_df_parenthesis_1 <<- "Df(1)"
  txt_df2 <<- "df2"
  txt_df_parenthesis_2 <<- "Df(2)"
  txt_df_denom <<- "df.denom"
  txt_df_parenthesis_denom <<- "Df (dnom)"
  txt_df_effect <<- "df.effet"
  txt_df_num <<- "df.num"
  txt_df_parenthesis_num <<- "Df (num)"
  txt_df_predictor <<- "df predictor"
  txt_df_residual <<- "df.resid"
  txt_df_residuals <<- "df.residuals"
  txt_delta_r_squared <<- "Delta R.two"
  txt_error <<- "Error"
  txt_error_BP <<- "Error.BP"
  txt_error_spearman <<- "Error.Spearman"
  txt_error_dot_standard_short <<- "error.st"
  txt_error_dot_standard <<- "error.standard"
  txt_error_dot_standard <<- "Error.standard"
  txt_space <<- "space"
  txt_estimator <<- "estimator"
  txt_global_model_estimate <<- "Global model estimation"
  txt_hf_p_value <<- "HF.p.value"
  txt_ci_inferior <<- "CI Inf"
  txt_ci_inferior_limit <<- "CI lim inf"
  txt_ci_superior_limit <<- "CI lim sup"
  txt_ci_superior <<- "CI Sup"
  txt_large <<- "large"
  txt_large_half <<- "large - 0.5"
  txt_inferior_limit <<- "lim.inf"
  txt_ci_inferior_limit_dot <<- "lim.inf.CI"
  txt_ci_inferior_limit_dot <<- "Lim.inf.CI"
  txt_ci_superior_limit <<- "lim.sup"
  txt_ci_superior_limit_dot <<- "lim.sup.CI"
  txt_ci_superior_limit_dot <<- "Lim.sup.CI"
  txt_r_squared_matrix <<- "matrix r.two"
  txt_truncated_m <<- "M.truncated"
  txt_multiplied_by <<- "multiplied.by"
  txt_dot_cleaned <<- ".cleaned"
  txt_cleaned <<- "cleaned"
  txt_bootstrap_dot_number <<- "Number.bootstraps"
  txt_odd_ratio_dot <<- "Odd.ratio"
  desc_install_bad_packages <<- "Package.mal.installes"
  desc_install_correct_packages <<- "packages.installes.correctement"
  txt_critical_p_corrected <<- "crit.p.corrected"
  txt_percentile_inferior_limit_dot <<- "Percentile.lim.inf"
  txt_percentile_superior_limit_dot <<- "Percentile.lim.sup"
  txt_percentage_removed_obs <<- "Percentage.obs.removed"
  txt_percent_removed_obs <<- "Percent.obs.removed"
  txt_r_dot_square <<- "r.square"
  txt_r_square <<- "R square"
  txt_r_dot_square <<- "R.square"
  txt_r_dot_two <<- "r.two"
  txt_r_dot_two <<- "R.two"
  txt_r_dot_two_adjusted <<- "R.two.aj"
  txt_log_regression_dot <<- "Regressions.logistic"
  txt_multiple_regressions_dot <<- "regressions.multiples"
  txt_multiple_regressions_dot <<- "Regressions.multiples"
  txt_rho_dot_square <<- "rho.two"
  txt_critical_dot_threshold <<- "critic.threshold"
  txt_critical_dot_threshold <<- "Critic.threshold"
  txt_spearman_df <<- "Spearman.df"
  txt_specificity <<- "specifity"
  txt_ultrawide <<- "ultra wide"
  txt_ultrawide <<- "ultrawide"
  txt_ultrawide_val <<- "ultra wide - 0.707"
  txt_absolute_dot_val <<- "value.absolute."
  txt_contrast_dot_val <<- "Value.contrast"
  txt_critical_dot_val <<- "Value.critical"
  txt_p_dot_val <<- "p.value"
  txt_p_dot_val_lilliefors <<- "p.value Llfrs"
  txt_p_dot_val_sw <<- "p.value SW"
  txt_test_dot_val <<- "test.value"
  txt_z_dot_val <<- "Z.value"
  txt_value <<- "value"
  txt_vector_length_zero <<- "vector of length zero"
  txt_kendall_w <<- "Kendall.W"
  txt_synthesis <<- "Synthesis"
  txt_truncated_mean_0_2 <<- "Test on truncated mean 0.2"
  txt_cramer_v_square <<- "V.square"
  txt_effect_size_dot <<- "Effect.size"
  txt_gg_p_value <<- "GG.p.value"
  txt_var_explained_dot <<- "Var.explained"
   V.sq<<-"V.squared"
}
